
stages:
  - stage: build and deploy
    variables:
      - group: NEXT-WEB-APP
    jobs:
    - job: publish
      steps:
        - task: AzureStaticWebApp@0
          inputs:
            azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_TOKEN)
            app_location: "/"
            api_location: ""
            output_location: ""
            is_static_export: true